### PR TITLE
Hashlink Support

### PR DESCRIPTION
**Pull request by Apprentice-Alchemist**
Tested with the example project.

### CODE REVIEW

**Comment by Tanz0rz** [comment]
Wow thanks for doing this! Will go through this early this week and also give the `HashLink` build a try on some of my games.

**Comment by chosencharacters** [comment]
Tested it and it works with my game :D

**Comment by Tanz0rz** [comment]
I am trying to build one of my games with HashLink and am hitting compilation errors. Here is what I have run

- Install HashLink via `haxelib`:
```
> haxelib install hashlink
Download complete: 0.25KB in 0.7s (0.3KB/s)
Download complete: 9.55KB in 0.9s (10.2KB/s)
Installing hashlink...
  Current version is now 0.1.0
Done
```

- Try to build game with `lime`'s `hl` command:
```
> lime test hl
src\module.c(321) : FATAL ERROR : Failed to load library ssl.hdll
```

I found [this thread](https://community.openfl.org/t/hashlink-build-missing-hdll/12594) from July of this year which made me suspect my `lime` version. I updated it to version 7.8.0, but that didn't change anything. 

Is this a known issue? Is there other requirements to building HashLink games through `lime`?

**Comment by chosencharacters** [comment]
Are you using the latest version of Haxe? Namely 4.0 and later?

**Comment by Apprentice-Alchemist** [comment]
Lime only bundles the bare minimum in terms of hl libs. So stuff like ssl, `hl.Format` and `hl.uv.*` don't work.
The easieast fix would be to grab the 1.10 binaries [here](https://github.com/HaxeFoundation/hashlink/releases/tag/1.10) and add them to your `PATH` or copying them over to `export/hl/bin`. (1.11+ binaries won't work because they're 64 bit)

**Comment by Apprentice-Alchemist** [comment]
Closed in favour of #12

**Pull request closed without merging**
